language: node_js
node_js:
  - 14.17.0

notifications:
  email: false

cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
